package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/SaadBelfqih/apple-ads-cli/cmd"
	"github.com/spf13/cobra/doc"
)

func main() {
	var outDir string
	flag.StringVar(&outDir, "out", "docs/commands", "Output directory for generated command docs")
	flag.Parse()

	if err := os.MkdirAll(outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir %s: %v\n", outDir, err)
		os.Exit(1)
	}

	root := cmd.RootCommand()

	prepender := func(filename string) string {
		rel := filepath.ToSlash(filename)
		return fmt.Sprintf("<!-- Generated by `go run ./tools/gendocs` on %s. DO NOT EDIT. -->\n<!-- Source: %s -->\n\n",
			time.Now().UTC().Format(time.RFC3339),
			rel,
		)
	}

	linkHandler := func(name string) string { return name }

	if err := doc.GenMarkdownTreeCustom(root, outDir, prepender, linkHandler); err != nil {
		fmt.Fprintf(os.Stderr, "generate docs: %v\n", err)
		os.Exit(1)
	}
}
